### ISSUE TITLE
Historias de usuario

### ISSUE THREAD

**Issue by TheArchKnight** [TheArchKnight/parranda-navide-a#4]
Crear las historias de usuario en base a los requerimientos documentados.

**Comment by RogerVeraL** [comment]
Plantilla para la redacción de las historias de usuario
[user_story_format.md](https://github.com/user-attachments/files/17987791/user_story_format.md)

**Comment by RogerVeraL** [comment]
Listado y Asignación de Historias de Usuario
[user_stories_list.md](https://github.com/user-attachments/files/18000689/user_stories_list.md)
Roger Vera: 1-7
Angel Brand: 8 -15
Diego Gracia: 16 - 22 
Angel Mazo: 23 - 26

**Comment by TheArchKnight** [comment]
> Listado y Asignación de Historias de Usuario [user_stories_list.md](https://github.com/user-attachments/files/18000689/user_stories_list.md) Roger Vera: 1-7 Angel Brand: 8 -15 Diego Gracia: 16 - 22 Angel Mazo: 23 - 26

Lo ideal seria añadir la lista de historias de usuario asi como el formato bajo la carpeta docs.

Edit: La lista de historias de usuario asi como el formato ya se encuentran en la carpeta docs. Revisar la rama adjunta a este issue.

**Comment by AngelBrand1** [comment]
cerrado
